#!/bin/bash
#--------------------------
# project specific substitution commands

rm -rf ../docker-compose.yml
envsubst < "templates/docker-compose.yml" > "../docker-compose.yml"

mkdir owncloud
rm -rf owncloud/config.php
envsubst < "templates/config.php" > "owncloud/config.php"

mkdir ../maintain
rm -rf ../maintain/backup_db
envsubst < "templates/backup_db" > "../maintain/backup_db"
chmod 755 ../maintain/backup_db

rm -rf ../maintain/crontab.info
envsubst < "templates/crontab.info" > "../maintain/crontab.info"

rm -rf ../start_owncloud
envsubst < "templates/start_owncloud" > "../start"
chmod 755 ../start

rm -rf themes/jc-cloud-theme/defaults.php
envsubst < "templates/theme-defaults.php" > "themes/jc-cloud-theme/defaults.php"

rm -rf themes/jc-cloud-theme/core/css/styles.css
envsubst < "templates/theme-styles.css" > "themes/jc-cloud-theme/core/css/styles.css"

cd ..

sudo mkdir $MAIN_DIR_DATA
sudo mkdir $DIR_HTML
sudo mkdir $DIR_DATA
sudo mkdir $DIR_DATABASE
sudo mkdir $DIR_DATABASE_INIT
sudo mkdir $DIR_BACKUP

cd $MAIN_DIR_DATA
sudo chown www-data html/
sudo chown www-data data/
sudo chown 999 database/


